# Generated by Django 5.1 on 2024-08-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venta', models.CharField(max_length=100, unique=True)),
                ('documento_comprador', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario')),
                ('codigo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historialventas')),
            ],
        ),
    ]
