# Generated by Django 5.1 on 2024-08-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historialventas_fecha_historialventas_sede_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialventas',
            name='codigo_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='codigo_venta',
        ),
    ]
