# Generated by Django 5.1 on 2024-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_historialventas_codigo_prenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='umbral_inventario',
            field=models.IntegerField(default=10),
        ),
    ]
