# Generated by Django 5.1 on 2024-08-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventario_umbral_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('institucion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_cedula', models.CharField(max_length=20)),
                ('cliente_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_BOGOTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_CALI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_MELGAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_PALANQUERO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_TRESESQUINAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_VILLAVICENCIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prenda', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_inventario', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cuentacobro')),
            ],
        ),
    ]
