# Generated by Django 5.1 on 2024-08-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cuentacobro_inventario_bogota_inventario_cali_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('institucion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_cedula', models.CharField(max_length=20)),
                ('cliente_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario_BOGOTA',
        ),
        migrations.DeleteModel(
            name='Inventario_CALI',
        ),
        migrations.DeleteModel(
            name='Inventario_MELGAR',
        ),
        migrations.DeleteModel(
            name='Inventario_PALANQUERO',
        ),
        migrations.DeleteModel(
            name='Inventario_TRESESQUINAS',
        ),
        migrations.DeleteModel(
            name='Inventario_VILLAVICENCIO',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='cliente_cedula',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='cliente_direccion',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='codigo_producto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='departamento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='institucion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='municipio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detallecuentacobro',
            name='cuenta_cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cuentacobro1'),
        ),
    ]
