# Generated by Django 5.1 on 2024-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cuentacobro1_delete_inventario_bogota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecuentacobro',
            name='cuenta_cobro',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='valor_unitario',
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='institucion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='nit',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='productos',
            field=models.ManyToManyField(to='core.producto'),
        ),
        migrations.DeleteModel(
            name='CuentaCobro1',
        ),
        migrations.DeleteModel(
            name='DetalleCuentaCobro',
        ),
    ]
