# Generated by Django 5.1 on 2024-08-28 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_remove_detallecuentacobro_cuenta_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobro',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='departamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='municipio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='nit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
