# Generated by Django 5.1 on 2024-08-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cuentacobro_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='nit',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
