# Generated by Django 5.1 on 2024-08-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cuentacobro_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='nit',
            field=models.CharField(max_length=50),
        ),
    ]
