# Generated by Django 5.1 on 2024-09-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cuentacobro_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor_unitario',
        ),
        migrations.CreateModel(
            name='HistorialCuentasdeCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
