# Generated by Django 5.1 on 2024-09-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_remove_producto_valor_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacobro',
            name='productos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='historialcuentasdecobro',
            name='cliente',
            field=models.CharField(max_length=60),
        ),
    ]
