# Generated by Django 5.1 on 2024-09-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_cuentacobro_productos_alter_cliente_nit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaCobro',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
